### ISSUE TITLE
Compiled code

### ISSUE THREAD

**Issue by shekofte** [paator/eJayDecompressor#1]
Hi Mr pattor
I am new to github and nostalgically search for ejay lead me here ...
How can I have your converter as executable application ?
Currently I don't have any programming environment on my desktop !
Thanks a lot for your help !
Your sincerely Fereydoon Shekofte

**Comment by paator** [comment]
Hello @shekofte, sorry for late reply. I will provide compiled .exe later today as soon as I get back from work.

**Comment by paator** [comment]
Hey @shekofte, I compiled .exe and uploaded it as release on github. Please let me know if it does work for you.
Best regards
