### ISSUE TITLE
big PXD files

### ISSUE THREAD

**Issue by INFU-AV** [paator/eJayDecompressor#3]
Newer Ejays compress the PXD files into huge 400Mb files, which makes the program unable to unpack them - each of those always has .inf file right next to them, which probably instructs how its compressed

is it possible to add to the program some option of handling such files?

**Comment by paator** [comment]
Hey, thanks for your message.
Yes, I think it should be possible. Gonna report back as soon as I find something.
Cheers!

**Comment by paator** [comment]
Sorry it takes so long @INFU-AV, I'm quite busy at the moment but I'll definitely look into it.
If someone wants to do this earlier, feel free to open a pull request. 😉

**Comment by Tolsi** [comment]
Hi, do you have an example small PXD what that app can convert to WAV? Or what Ejay version contains them?

**Comment by Tolsi** [comment]
It looks like PXDs from large files are different from PXDs in older versions and the RWavToTemp function cannot decompress them as is. Perhaps you need to pass special parameters, it was not possible to sniff them yet. Can you help me with it?

**Comment by paator** [comment]
Hi @Tolsi, thanks for making draft PR! I'll look into it after the weekend!

**Comment by Tolsi** [comment]
I used a debugger and found that newer versions of eJay use a different loops loading function - `ADecompress` from `eJ_Tool.dll`. Work in progress...
