### ISSUE TITLE
How to extract dance eJay 2 and 3?

### ISSUE THREAD

**Issue by BKVad1m** [paator/eJayDecompressor#4]
![2021-10-31](https://user-images.githubusercontent.com/76803825/139573515-61d1471b-de94-4a1e-a10c-44ab7e95c1d1.png)

**Comment by paator** [comment]
Try to run my tool in the root folder of eJay. It will try to find all hidden PXD files in every folder underneath recursively.

**Comment by BKVad1m** [comment]
![image](https://user-images.githubusercontent.com/76803825/139700873-cbdbfb71-27e1-40b2-a6ce-a651533a0404.png)
![image](https://user-images.githubusercontent.com/76803825/139700941-5f7f4159-9bf8-4076-bbfd-baf4c2522e8e.png)
![image](https://user-images.githubusercontent.com/76803825/139700977-913eb339-716e-4bec-b6f3-935ef7a02982.png)
I'm tried. I cannot extracted

**Comment by paator** [comment]
Are there any .pxd files you can locate manually?

**Comment by BKVad1m** [comment]
> Are there any .pxd files you can locate manually?

no

**Comment by paator** [comment]
I'm sorry but this means my application can't help you.
At the moment it only converts .pxd to .wav files, so if some samples are packed in different file format, I can't help.
Maybe I'll do some research and add more support in future.

**Comment by BKVad1m** [comment]
have you path (dance20.inf) to extract samples from Dance eJay 2?
