### ISSUE TITLE
Does not work with the re-released Dance Ejay

### ISSUE THREAD

**Issue by Cafetorium** [paator/eJayDecompressor#6]
Dance EJay etc were re-released so that they run on 32/64 bit systems, and no longer use pxd32d5_d4.dll and eJ_Tool.dll.
They now have PXD32CL1.DLL and PXD98DB.DLL
There is no eJ_Tool.dll.

**Comment by paator** [comment]
I will look into it after fixing current code, which doesn't use .NET 6. @Tolsi maybe you know the answer?

**Comment by Tolsi** [comment]
I newer found the pxd32d5_d4.dll, but I used pxd32d5.dll and renamed it to pxd32d5_d4.dll
In addition, I do not understand the problem of putting them in the repository, forcing the user to search for some libraries is a mockery. 
[Here they are](https://mega.nz/file/NQcVEKZZ#ES_Yj0Cb3CKsiLnZpbHw2gIHgByWV8aQBcVIF1bT6s4)

**Comment by paator** [comment]
The answer feels really natural to me - if user provides their own .dll, responsibility of having an original copy of software lies on the user. User decides if they want to buy the software and use .dll included with it or pirate it.

With including .dll on public repository, we're basically sharing illegal software. I won't agree to this happening on my repository, sadly. If you want to create your own with shared .dll, feel free to.

This program and its repository assumes the .dll you use is obtained in a legal way. Perhaps I should include that information in README.
