### ISSUE TITLE
64 bits problem on v1.2

### ISSUE THREAD

**Issue by lcha78** [paator/eJayDecompressor#7]
Hello paator,
I have a problem with PXDConverter v1.2. It's a 64bit exe trying to load 32 bits dll and I have the following error  : 
On single PXD files : "Couldn't find or initialize pxd32d5_d4.dll. Be sure to locate it in the same location as Converter exe file."
On multi PXD packages : "Error during creating temporary buffer file via using external eJay dll method. Are you sure that PXD file is valid? Detailed message: Tentative de chargement d'un programme de format incorrect. (0x8007000B)"

When I use PXDConverter v1.1 (32 bits exe) on single PXD files It's working correctly.

**Comment by paator** [comment]
Hi @lcha78 👋 
Thank you for opening the issue. I'll look into it as soon as possible :)

**Comment by paator** [comment]
Hello @lcha78, I'm currently working on resolving this problem.
Fixed version should be available soon.

**Comment by paator** [comment]
@lcha78 
The issue should be resolved in the new version. I'm gonna release 1.3 today which will include some major bugfixes made by @wermipls in pull request https://github.com/paator/eJayDecompressor/pull/8. The .exe file will be 32bit.

**Comment by paator** [comment]
New version released: https://github.com/paator/eJayDecompressor/releases/tag/v1.3
It should fix the issue you mentioned. Closing this issue for now. Reopen if needed:)

**Comment by lcha78** [comment]
Hello @paator 
Great ! Good job.
Only one thing to note: Now .NET **x86 (32 bits)** runtime is needed. 
I think it should be mentioned in README.md

**Comment by paator** [comment]
Thanks for mentioning that. I've just updated the readme file.
